### PR TITLE
Option to split waypoints to multiple routes if exceeding waypoint limit

### LINKED ISSUE #109: Add option to split waypoints to multiple routes if exceeding waypoint limit
Directions API has limit of 10 or 25 waypoints per route. So `waypoints` array is size is limited to those numbers.

There is a workaround where you can use multiple `MapViewDirections` components with connected origin/destination which appear to the user as one route. I have implemented this logic inside my project.

My idea is to add `boolean` type prop `splitWaypoints` or similar that will automatically do this under the hood because I think many people have and would have a need for this.

I am open to submit pull request and implement dis if there is interest,
What do you think? @bramus

### PR DESCRIPTION
**Pull request by capJavert**
Resolves #109 

- [x] Prop implementation 
- [x] Waypoints split logic
- [x] Multiple Polyline rendering
- [x] Update README

### CODE REVIEW

**Comment by capJavert** [comment]
@bramus I did initial implementation for this feature regarding our discussion in #109  

Let me know how this looks :)

**Comment by capJavert** [comment]
@bramus did you have time to check this out?

Would appreciate that, tnx!

**Comment by bramus** [comment]
Hi @capJavert, thanks for this PR!

_(I was away on vacation and had some catching up to do … hence this late reply)_

I checked your code out in the [react-native-maps-example](https://github.com/bramus/react-native-maps-directions-example) example app (*) and did notice this big warning in the console when adding a waypoint:

Screenshot 2019-12-06 at 10 39 57

Could you check that out before I merge this one?

Thanks!

---

_(*) Test it yourself using `yarn add 'ssh://git@github.com:capJavert/react-native-maps-directions.git#feature/split-waypoints'`_

**Comment by capJavert** [comment]
Hey @bramus no worries. I adjusted some stuff but... :)

I was only able to get this error sometimes after RN fast refresh triggered update. I think that stale keys was due to combination of fast refresh and componentDidUpdate condition. 

So I added:

1. splitWaypoints to `componentDidUpdate` condition (noticed that when chaning new prop `true`/`false` error would trigger more often
2. Adjusted ids when `splitWaypoints` is off

After updates in last commit I was no longer able to get this error but I think that best thing would be to refactor this component with `useEffect` and functional components implementation some time in the future. 

This component would greatly benefit from this and future development would be more easy to work and debug. Also open for collaborating on this.

let me know!

**Comment by bramus** [comment]
I still saw the same issue with your updated coded @capJavert. Now it was stating that the `'singleWaypoint'` key was duplicated. Going over the limit lead to an Error in my test application.

Looking at the code I could see where things were going wrong: you try to render multiple polylines. This is not necessary, as 1 single polyline _(with all cooordinates combined)_ will also do.

Adjusting your code I could also see an issue with it: calling `setState` multiple times _(from within each request handler)_ can lead to data loss, as React will batch those calls. Limiting yourself to one `setState()` call – after all calls had been made – is the solution for this.

I've also reworked the batching of the waypoints into routes/chunks whilst I was at it.

What do you think?

**Comment by capJavert** [comment]
All I can say is: "Nice work man!". I intially wen with multiple polyline because i though it would be easier to track but I like this solution better now. 

Good catch with multiple `setState` calls, makes sense.

**Pull request merged**
