### PR TITLE
Duration In Traffic

### PR DESCRIPTION
**Pull request by RodneyOnyi**
Change the duration to factor in traffic given that routes are rarely traffic free.

### CODE REVIEW

**Comment by bramus** [comment]
Hi, this PR contains many formatting changes (change from tabs to spaces).
Please submit only the essential changes, and adhere to the formatting used.

**Comment by RodneyOnyi** [comment]
I have fixed the formatting please let me know if this okay to merge now.

**Comment by bramus** [comment]
Thanks for the changes @RodneyOnyi! PR by itself looks good now!

One issue though: when checking the API Docs [I see](https://developers.google.com/maps/documentation/directions/intro#DirectionsAdvanced) that the field `duration_in_traffic` is not always provided:

> Traffic information is used when all of the following apply (these are the conditions required to receive the `duration_in_traffic` field in the Directions response):
> 
> - The travel `mode` parameter is `"driving"`, or is not specified (`"driving"` is the default travel `mode`).
> - The request includes a valid `departure_time` parameter. The `departure_time` can be set to the current time or some time in the future. It cannot be in the past.
> - The request does not include stopover waypoints. If the request includes waypoints, prefix each waypoint with via: to influence the route but avoid stopovers.

Please harden the code so that it plays nice in scenarios where `duration_in_traffic` is not provided in the respone (falling back to `duration`).

**Comment by RodneyOnyi** [comment]
Thanks for the catch, let me change that and resubmit to accommodate for the missing link

**Comment by RodneyOnyi** [comment]
Fail over added for cases where `duration_in_traffic` not available

**Comment by bramus** [comment]
Merged. Thanks!

**Pull request merged**
